services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
#      - db_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8070:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - "7000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - php-fpm
#volumes:
#    db_data: